#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: mygit [git url] (license) (.gitignore)"
    exit 1
fi

echo "Setting up git repository..."
git init

if [ $# -ge 2 ]; then
    echo "Generating license..."
    license-generator install $2,, > LICENSE
    git add LICENSE
fi

if [ $# -ge 3 ]; then
    echo "Downloading .gitignore..."
    wget "https:/raw.githubusercontent.com/github/gitignore/master/$3.gitignore"
    git add .gitignore
fi

echo "Pushing files to $1 in branch master"
git commit -m "Repo initialized by mygit" -m "https://github.com/GoodPro712/mygit/"
git branch -M master
git remote add origin $1
git push -u origin master

echo "Finished setting up repository!"
exit 0
